group = {
    'other': ['explosives', 'hydrogenfuel', 'mineraloil', 'pesticides', 'syntheticreagents',
            'surfacestabilisers', 'nerveagents', 'deltaphoenicispalms', 'toxandjivirocide',
            'anduligafireworks', 'hiporganophosphates', 'korokungpellets', 'water', 'hydrogenperoxide',
            'liquidoxygen', 'clothing', 'consumertechnology', 'domesticappliances', 'evacuationshelter',
            'alacarakmoskinart', 'eleuthermals', 'eshuumbrellas', 'karetiicouture', 'njangarisaddles',
            'kinagoviolins', 'ngunamodernantiques', 'rajukrumulti-stoves', 'tiolcewaste2pasteunits',
            'ophiuchexinoartefacts', 'havasupaidreamcatcher', 'jaradharrepuzzlebox', 'uzumokulow-gwings',
            'altairianskin', 'jotunmookah', 'zeesszeantgrubglue', 'momusbogspaniel', 'leatheryeggs',
            'vidavantianlace', 'jaquesquinentianstill', 'soontillrelics', 'thehuttonmug', 'crystallinespheres',
            'survivalequipment', 'beer', 'liquor', 'narcotics', 'tobacco', 'wine', 'eraninpearlwhiskey',
            'lucanonionhead', 'motronaexperiencejelly', 'onionhead', 'rusanioldsmokey', 'tarachspice',
            'wolffesh', 'wuthielokufroth', 'bootlegliquor', 'lavianbrandy', 'lyraeweed', 'konggaale',
            'bastsnakegin', 'thrutiscream', 'kamitracigars', 'yasokondileaf', 'chateaudeaegaeon',
            'saxonwine', 'centaurimegagin', 'geawendancedust', 'gerasiangueuzebeer', 'burnhambiledistillate',
            'pavoniseargrubs', 'indibourbon', 'leestianeviljuice', 'azuremilk', 'onionheadalphastrain',
            'onionheadbetastrain', 'polymers', 'semiconductors', 'superconductors', 'meta-alloys',
            'ceramiccomposites', 'medbstarlube', 'insulatingmembrane', 'cmmcomposite', 'micro-weavecoolinghoses',
            'neofabricinsulation', 'atmosphericprocessors', 'cropharvesters', 'marineequipment', 'microbialfurnaces',
            'mineralextractors', 'powergenerators', 'waterpurifiers', 'thermalcoolingunits', 'skimmercomponents',
            'geologicalequipment', 'buildingfabricators', 'volkhabbeedrones', 'wulpahyperboresystems', 'noneuclidianexotanks',
            'giantverrix', 'articulationmotors', 'hnshockmount', 'emergencypowercells', 'powerconverter', 'energygridassembly',
            'powertransferbus', 'radiationbaffle', 'exhaustmanifold', 'reinforcedmountingplate', 'heatsinkinterlink',
            'magneticemittercoil', 'modularterminals', 'iondistributor', 'aluminium', 'beryllium', 'cobalt', 'copper',
            'gallium', 'gold', 'indium', 'lithium', 'palladium', 'platinum', 'silver', 'tantalum', 'titanium', 'uranium',
            'osmium', 'thorium', 'thallium', 'lanthanum', 'bismuth', 'hafnium178', 'sothiscrystallinegold',
            'praseodymium', 'samarium', 'bauxite', 'bertrandite', 'coltan', 'gallite', 'indite', 'lepidolite',
            'rutile', 'uraninite', 'painite', 'pyrophyllite', 'moissanite', 'goslarite', 'cryolite', 'cherbonesbloodcrystals',
            'ngadandarifireopals', 'taaffeite', 'jadeite', 'bromellite', 'lowtemperaturediamonds', 'methanolmonohydrate',
            'lithiumhydroxide', 'methaneclathrate', 'imperialslaves', 'slaves', 'masterchefs', 'advancedcatalysers',
            'animalmonitors', 'aquaponicsystems', 'auto-fabricators', 'bioreducinglichen', 'computercomponents', 'h.e.suits',
            'landenrichmentsystems', 'resonatingseparators', 'robotics', 'structuralregulators', 'muonimager', 'xihebiomorphiccompanions',
            'azcancriformula42', 'nanobreakers', 'telemetrysuite', 'microcontrollers', 'hardwarediagnosticsensor',
            'medicaldiagnosticequipment', 'leather', 'naturalfabrics', 'syntheticfabrics', 'belalansrayleather', 'damnacarapaces',
            'rapabaosnakeskins', 'vanayequiceratomorphafur', 'bankiamphibiousleather', 'tiegfriessynthsilk', 'chameleoncloth',
            'conductivefabrics', 'militarygradefabrics', 'biowaste', 'chemicalwaste', 'scrap', 'toxicwaste', 'limpet', 'airelics',
            'antiquities', 'sap8corecontainer', 'trinketsofhiddenfortune', 'tradedata', 'occupiedcryopod', 'blackbox', 'militaryplans',
            'ancientartefact', 'rareartwork', 'experimentalchemicals', 'rebeltransmissions', 'prototypetech', 'technicalblueprints',
            'thargoidsensor', 'militaryintelligence', 'salvageablewreckage', 'encrypteddatastorage', 'personaleffects',
            'commercialsamples', 'tacticaldata', 'assaultplans', 'encryptedcorrespondence', 'diplomaticbag', 'scientificresearch',
            'scientificsamples', 'politicalprisoner', 'hostage', 'geologicalsamples', 'unstabledatacore', 'occupiedescapepod',
            'datacore', 'galactictravelguide', 'mysteriousidol', 'prohibitedresearchmaterials', 'antimattercontainmentunit',
            'spacepioneerrelics', 'fossilremnants', 'thargoidprobe', 'preciousgems', 'thargoidlink', 'thargoidbiologicalmatter',
            'thargoidresin', 'thargoidtechnologysamples', 'ancientrelic', 'ancientorb', 'ancientcasket', 'ancienttablet',
            'ancienturn', 'ancienttotem', 'smallsurveydatacache', 'largesurveydatacache', 'damagedescapepod', 'earthrelics',
            'thargoidscouttissuesample'],
    'medicines': ['agri-medicines', 'basicmedicines', 'combatstabilisers', 'performanceenhancers', 'progenitorcells',
                  'terramaterbloodbores', 'kachiriginfilterleeches', 'aganipperush', 'watersofshintara', 'honestypills',
                  'vherculisbodyrub', 'vegaslimweed', 'taurichimes', 'pantaaprayersticks', 'fujintea', 'alyabodysoap',
                  'advancedmedicines'],
    'weapons': ['non-lethalweapons', 'personalweapons', 'reactivearmour', 'battleweapons', 'kamorinhistoricweapons',
                'landmines', 'borasetanipathogenetics', 'hip118311swarm', 'holvaduellingblades', 'gilyasignatureweapons'],
    'foods': ['algae', 'animalmeat', 'coffee', 'fish', 'foodcartridges', 'fruitandvegetables', 'grain', 'syntheticmeat',
              'tea', 'hip10175bushmeat', 'albinoquechuamammoth', 'utgaroarmillennialeggs', 'witchhaulkobebeef', 'karsukilocusts',
              'giantirukamasnails', 'baltahsinevacuumkrill', 'cetirabbits', 'anynacoffee', 'cd-75kittenbrandcoffee',
              'gomanyauponcoffee', 'chieridanimarinepaste', 'esusekucaviar', 'livehecateseaworms', 'helvetitjpearls',
              'hipproto-squid', 'coquimspongiformvictuals','edenapplesofaerial', 'neritusberries', 'ochoengchillies',
              'deuringastruffles', 'hr7221wheat', 'jarouarice', 'sanumadecorativemeat', 'ethgrezeteabuds', 'ceremonialheiketea',
              'tanmarktranquiltea', 'aepyornisegg', 'haidneblackbrew', 'voidextractcoffee', 'ltthypersweet', 'mechucoshightea',
              'mokojingbeastfeast', 'mukusubiichitin-os', 'mulachigiantfungus', 'wheemetewheatcakes', 'aroucaconventualsweets',
              'orrerianviciousbrew', 'uszaiantreegrub', 'disomacorn']
    }
